// Generated by https://quicktype.io

export default class PermissionEntity {
	permissionCode:      string;
	moduleName:          string;
	permissionName:      string;
	permissionLevel:     number;
	permissionCreatedAt: string;

	constructor(permission?) {
		if(!permission) return null;
		Object.assign(this, permission)
	}

	static createListPermission(listPermission){
		if(!Array.isArray((listPermission))) return [];
		return listPermission.map((permission)=> new PermissionEntity(permission))
	}
}
