class RoleEntity {
  roleId: string;
  roleName: string;
  roleCode: string;
  groupId: string;
  roleLevel: number;
  rolePermissions: string;
  permissions: string[];
  permissionCodes: string[];
  createAt: string;
  businessOrganizationId: string;
  roleDescription: null;
  roleCreatedAt: string;
  numberOfUserInRole: number;
  constructor ( role?) {
    if ( !role ) return null;
    Object.assign( this, role );

    if ( role?.permissions ) {
      this.permissions = role?.permissions.map( i => i.permissionCode );
    }
  }

  static createListRole ( listRole ) {
    if ( !Array.isArray( listRole ) ) return [];
    return listRole.map( ( Role ) => {
      return new RoleEntity( Role );
    } );
  }
}

export default RoleEntity;


// Generated by https://quicktype.io

